CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY,name VARCHAR(120),email VARCHAR(160) UNIQUE,password_hash TEXT,role VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS articles (id SERIAL PRIMARY KEY,title TEXT,source VARCHAR(120),category VARCHAR(80),sentiment VARCHAR(30),summary TEXT,url TEXT,status VARCHAR(30) DEFAULT 'PUBLISHED',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS insights (id SERIAL PRIMARY KEY,headline TEXT,metric VARCHAR(120),value VARCHAR(120),trend VARCHAR(40),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs (id SERIAL PRIMARY KEY,user_email VARCHAR(160),action VARCHAR(120),resource VARCHAR(120),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
